### ISSUE TITLE
written.nodeify is not a function

### ISSUE THREAD

**Issue by Macil** [00dani/gulp-dest-atomic#1]
I get this error when I try to use gulp-dest-atomic. I'm using Node 6.

```
/Users/chris/Coding/streak/MailFoo/node_modules/gulp-dest-atomic/index.js:63
    written.nodeify(done);
            ^

TypeError: written.nodeify is not a function
    at writeContents (/Users/chris/Coding/streak/MailFoo/node_modules/gulp-dest-atomic/index.js:63:13)
    at /Users/chris/Coding/streak/MailFoo/node_modules/gulp-dest-atomic/index.js:104:13
    at /Users/chris/Coding/streak/MailFoo/node_modules/mkdirp/index.js:48:26   
    at FSReqWrap.oncomplete (fs.js:117:15)
```

It looks like gulp-dest-atomic is assuming that written is a Bluebird promise returned from fs-promise, but it doesn't look like fs-promise is guaranteed to return a Bluebird promise.

**Comment by 00dani** [comment]
Whoops, I'd thought Bluebird would always be used because it's listed in `package.json`, but it looks like `any-promise` requires you to register the desired promise lib explicitly.

There's really no _need_ to depend on Bluebird for that one call so I'll just change it to use the standard promise API instead.
